### PR TITLE
Starting VS Documentation

### PR DESCRIPTION
**Pull request by LeOctavius**

### CODE REVIEW

**Comment by Equalizer24K** [comment]
Hi kreusada! Downloaded this thinking I'd be one step closer to inventing mobile coding, I was wrong.
"If you want something, and it doesn't exist, invent it" - Edison

**Comment by KREUSADA** [comment]
Hey Equalizer, this cog is currently under development and shouldn't be downloaded anyway, its an rst for my docs. I'm not quite sure what you are trying to converse to me.

**Comment by Equalizer24K** [comment]
Oh I'm sry I meant github in general lol

**Comment by KREUSADA** [comment]
Ok, please stop commenting here. If you need help you can contact me in the development server

**Pull request merged**
